# Generated by Django 6.0.3 on 2026-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=255)),
                ("farm_location", models.TextField()),
                ("farm_address", models.TextField(blank=True, null=True)),
                (
                    "farm_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area in acres/hectares",
                        max_digits=10,
                    ),
                ),
                ("flock_size", models.IntegerField(default=0)),
                ("farm_type", models.CharField(max_length=100)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PoultryFlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flock_name", models.CharField(max_length=255)),
                ("breed", models.CharField(max_length=100)),
                ("hatch_date", models.DateField()),
                ("current_age_weeks", models.IntegerField(default=0)),
                ("total_count", models.IntegerField()),
                ("mortality_count", models.IntegerField(default=0)),
                (
                    "feed_consumption",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
