# Generated by Django 5.0.14 on 2026-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmerprofile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="poultryflock",
            options={"ordering": ["-created_at"]},
        ),
    ]
