# Generated by Django 5.0.14 on 2026-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetprofile",
            name="gps_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="vetprofile",
            name="gps_long",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
