# Generated by Django 5.0.14 on 2026-05-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vets", "0002_vetprofile_gps_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetprofile",
            name="is_admin_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
