# Generated by Django 5.0.14 on 2026-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vets", "0003_vetprofile_is_admin_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vetreview",
            options={"ordering": ["-created_at"]},
        ),
    ]
