# Generated by Django 5.0.14 on 2026-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_token",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
