# Generated by Django 6.0.3 on 2026-04-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0002_initial"),
        ("medical", "0001_initial"),
        ("vets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="vet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="vets.vetprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="vet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="vets.vetprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="medical.appointmentslot",
            ),
        ),
        migrations.AddField(
            model_name="appointmentstatushistory",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="medical.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_received",
                to="farmers.farmerprofile",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="flock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="farmers.poultryflock",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="vet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_written",
                to="vets.vetprofile",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_requests",
                to="farmers.farmerprofile",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="vet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="vets.vetprofile",
            ),
        ),
    ]
