# Generated by Django 5.0.14 on 2026-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ("-scheduled_start",)},
        ),
        migrations.AlterModelOptions(
            name="prescription",
            options={"ordering": ["-issued_date"]},
        ),
    ]
