# Generated by Django 6.0.3 on 2026-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("symptoms", models.TextField()),
                ("images", models.JSONField()),
                ("animal_type", models.CharField(max_length=100)),
                (
                    "predicted_disease",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIDiagnosisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_type", models.CharField(max_length=50)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("predicted_disease", models.CharField(max_length=255)),
                ("processing_time_ms", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("accuracy_score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("deployed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
