# Generated by Django 5.0.14 on 2026-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ecommerce/products/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
