# Generated by Django 5.0.14 on 2026-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="social/posts/"),
        ),
    ]
