# Generated by Django 6.0.6 on 2026-06-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_post_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
